version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://llmuser:llmpassword@db:5432/llm_audio_db
    volumes:
      - ../app:/app

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=llmuser
      - POSTGRES_PASSWORD=llmpassword
      - POSTGRES_DB=llm_audio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
